package com.petlife.modules.pet.application.usecase;

import com.petlife.modules.auth.domain.entity.User;
import com.petlife.modules.medication.application.port.MedicationRepositoryPort;
import com.petlife.modules.pet.application.port.ConsultationRepositoryPort;
import com.petlife.modules.pet.application.port.GetPetWeightHistoryPort;
import com.petlife.modules.pet.application.port.GroomingRepositoryPort;
import com.petlife.modules.pet.application.port.PetRepositoryPort;
import com.petlife.modules.pet.application.port.VaccinationPort;
import com.petlife.modules.pet.entity.Consultation;
import com.petlife.modules.pet.entity.Pet;
import com.petlife.modules.pet.entity.TimelineEventType;
import com.petlife.modules.pet.entity.Vaccination;
import com.petlife.modules.pet.entity.Grooming;
import com.petlife.modules.medication.domain.entity.Medication;
import com.petlife.modules.pet.infrastructure.dto.TimelineEventResponse;
import java.math.BigDecimal;
import com.petlife.shared.exception.BusinessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class GetPetTimelineUseCaseTest {

    @Mock
    private PetRepositoryPort petRepositoryPort;
    @Mock
    private VaccinationPort vaccinationPort;
    @Mock
    private ConsultationRepositoryPort consultationRepositoryPort;
    @Mock
    private GroomingRepositoryPort groomingRepositoryPort;
    @Mock
    private GetPetWeightHistoryPort getPetWeightHistoryPort;
    @Mock
    private MedicationRepositoryPort medicationRepositoryPort;

    @InjectMocks
    private GetPetTimelineUseCase getPetTimelineUseCase;

    private UUID userId;
    private UUID petId;
    private Pet pet;

    @BeforeEach
    void setUp() {
        userId = UUID.randomUUID();
        petId = UUID.randomUUID();

        User user = new User();
        user.setId(userId);

        pet = new Pet();
        pet.setId(petId);
        pet.setUser(com.petlife.modules.auth.infrastructure.persistence.mapper.UserMapper.toJpaEntity(user));
        pet.setName("Rex");
        pet.setBirthDate(null); // No birthdays generated by default
    }

    @Test
    void shouldReturnEmptyTimelineWhenNoEventsExist() {
        when(petRepositoryPort.findById(petId)).thenReturn(Optional.of(pet));
        when(vaccinationPort.findByPetId(petId)).thenReturn(Collections.emptyList());
        when(consultationRepositoryPort.findAllByPetId(petId)).thenReturn(Collections.emptyList());
        when(groomingRepositoryPort.findAllByPetId(petId)).thenReturn(Collections.emptyList());
        when(getPetWeightHistoryPort.getWeightHistory(petId)).thenReturn(Collections.emptyList());
        when(medicationRepositoryPort.findByPetId(petId)).thenReturn(Collections.emptyList());

        List<TimelineEventResponse> response = getPetTimelineUseCase.execute(petId, userId, null, 0, 20);

        assertNotNull(response);
        assertTrue(response.isEmpty());
    }

    @Test
    void shouldIncludeBirthdayEvents() {
        pet.setBirthDate(LocalDate.now().minusYears(2)); // 2 years old, should generate 2 birthday events

        when(petRepositoryPort.findById(petId)).thenReturn(Optional.of(pet));
        when(vaccinationPort.findByPetId(petId)).thenReturn(Collections.emptyList());
        when(consultationRepositoryPort.findAllByPetId(petId)).thenReturn(Collections.emptyList());
        when(groomingRepositoryPort.findAllByPetId(petId)).thenReturn(Collections.emptyList());
        when(getPetWeightHistoryPort.getWeightHistory(petId)).thenReturn(Collections.emptyList());
        when(medicationRepositoryPort.findByPetId(petId)).thenReturn(Collections.emptyList());

        List<TimelineEventResponse> response = getPetTimelineUseCase.execute(petId, userId, null, 0, 20);

        assertNotNull(response);
        assertEquals(2, response.size());
        assertEquals(TimelineEventType.BIRTHDAY, response.get(0).getType());
    }

    @Test
    void shouldReturnAggregatedEventsSortedDescending() {
        // Setup a vaccination event (10 days ago)
        Vaccination v = new Vaccination();
        v.setId(UUID.randomUUID());
        v.setVaccineName("Antirábica");
        v.setDateAdministered(LocalDate.now().minusDays(10));

        // Setup a consultation event (5 days ago)
        Consultation c = new Consultation();
        c.setId(UUID.randomUUID());
        c.setReason("Rotina");
        c.setDate(OffsetDateTime.now().minusDays(5));

        when(petRepositoryPort.findById(petId)).thenReturn(Optional.of(pet));
        when(vaccinationPort.findByPetId(petId)).thenReturn(List.of(v));
        when(consultationRepositoryPort.findAllByPetId(petId)).thenReturn(List.of(c));
        when(groomingRepositoryPort.findAllByPetId(petId)).thenReturn(Collections.emptyList());
        when(getPetWeightHistoryPort.getWeightHistory(petId)).thenReturn(Collections.emptyList());
        when(medicationRepositoryPort.findByPetId(petId)).thenReturn(Collections.emptyList());

        List<TimelineEventResponse> response = getPetTimelineUseCase.execute(petId, userId, null, 0, 20);

        assertNotNull(response);
        assertEquals(2, response.size());
        // The first one should be consultation (5 days ago) and then vaccination (10 days ago)
        assertEquals(TimelineEventType.CONSULTATION, response.get(0).getType());
        assertEquals(TimelineEventType.VACCINE, response.get(1).getType());
    }

    @Test
    void shouldFilterEventsByProvidedTypes() {
        Vaccination v = new Vaccination();
        v.setId(UUID.randomUUID());
        v.setVaccineName("Antirábica");
        v.setDateAdministered(LocalDate.now().minusDays(10));

        Consultation c = new Consultation();
        c.setId(UUID.randomUUID());
        c.setReason("Rotina");
        c.setDate(OffsetDateTime.now().minusDays(5));

        when(petRepositoryPort.findById(petId)).thenReturn(Optional.of(pet));
        when(vaccinationPort.findByPetId(petId)).thenReturn(List.of(v));
        when(consultationRepositoryPort.findAllByPetId(petId)).thenReturn(List.of(c));
        when(groomingRepositoryPort.findAllByPetId(petId)).thenReturn(Collections.emptyList());
        when(getPetWeightHistoryPort.getWeightHistory(petId)).thenReturn(Collections.emptyList());
        when(medicationRepositoryPort.findByPetId(petId)).thenReturn(Collections.emptyList());

        List<TimelineEventResponse> response = getPetTimelineUseCase.execute(
                petId, userId, List.of(TimelineEventType.VACCINE), 0, 20
        );

        assertNotNull(response);
        assertEquals(1, response.size());
        assertEquals(TimelineEventType.VACCINE, response.get(0).getType());
    }

    @Test
    void shouldThrowExceptionWhenPetNotFound() {
        when(petRepositoryPort.findById(petId)).thenReturn(Optional.empty());

        assertThrows(BusinessException.class, () -> 
            getPetTimelineUseCase.execute(petId, userId, null, 0, 20)
        );
    }

    @Test
    void shouldThrowExceptionWhenUserDoesNotOwnPet() {
        when(petRepositoryPort.findById(petId)).thenReturn(Optional.of(pet));
        UUID otherUserId = UUID.randomUUID();

        assertThrows(BusinessException.class, () -> 
            getPetTimelineUseCase.execute(petId, otherUserId, null, 0, 20)
        );
    }

    @Test
    void shouldMapGroomingAndWeightAndMedicationEvents() {
        // Grooming
        Grooming grooming = new Grooming();
        grooming.setId(UUID.randomUUID());
        grooming.setDate(LocalDate.now().minusDays(2));
        grooming.setProvider("PetShop");
        grooming.setNotes("Lindo");
        grooming.setPhotos(List.of("photo.jpg"));

        // Weight
        com.petlife.modules.pet.entity.WeightRecord weight = new com.petlife.modules.pet.entity.WeightRecord();
        weight.setId(UUID.randomUUID());
        weight.setWeightKg(BigDecimal.valueOf(15.5));
        weight.setRecordedAt(OffsetDateTime.now().minusDays(3));

        // Medication
        Medication med = new Medication();
        med.setId(UUID.randomUUID());
        med.setName("Bravecto");
        med.setDosage("1 cp");
        med.setFrequency(com.petlife.modules.medication.domain.entity.MedicationFrequency.DAILY);
        med.setStartDate(LocalDate.now().minusDays(10));
        med.setEndDate(LocalDate.now().plusDays(20));

        when(petRepositoryPort.findById(petId)).thenReturn(Optional.of(pet));
        when(vaccinationPort.findByPetId(petId)).thenReturn(Collections.emptyList());
        when(consultationRepositoryPort.findAllByPetId(petId)).thenReturn(Collections.emptyList());
        when(groomingRepositoryPort.findAllByPetId(petId)).thenReturn(List.of(grooming));
        when(getPetWeightHistoryPort.getWeightHistory(petId)).thenReturn(List.of(weight));
        when(medicationRepositoryPort.findByPetId(petId)).thenReturn(List.of(med));

        List<TimelineEventResponse> response = getPetTimelineUseCase.execute(petId, userId, null, 0, 20);

        assertNotNull(response);
        assertEquals(4, response.size()); // Grooming, Weight, Medication Start, Medication End
    }

    @Test
    void shouldPaginateCorrectly() {
        // Create 25 consultation events
        List<Consultation> consultations = new java.util.ArrayList<>();
        for (int i = 0; i < 25; i++) {
            Consultation c = new Consultation();
            c.setId(UUID.randomUUID());
            c.setReason("Test " + i);
            c.setDate(OffsetDateTime.now().minusDays(i));
            consultations.add(c);
        }

        when(petRepositoryPort.findById(petId)).thenReturn(Optional.of(pet));
        when(vaccinationPort.findByPetId(petId)).thenReturn(Collections.emptyList());
        when(consultationRepositoryPort.findAllByPetId(petId)).thenReturn(consultations);
        when(groomingRepositoryPort.findAllByPetId(petId)).thenReturn(Collections.emptyList());
        when(getPetWeightHistoryPort.getWeightHistory(petId)).thenReturn(Collections.emptyList());
        when(medicationRepositoryPort.findByPetId(petId)).thenReturn(Collections.emptyList());

        List<TimelineEventResponse> page0 = getPetTimelineUseCase.execute(petId, userId, null, 0, 20);
        List<TimelineEventResponse> page1 = getPetTimelineUseCase.execute(petId, userId, null, 1, 20);
        List<TimelineEventResponse> page2 = getPetTimelineUseCase.execute(petId, userId, null, 2, 20);

        assertEquals(20, page0.size());
        assertEquals(5, page1.size());
        assertEquals(0, page2.size());
    }
}
