spring:
  application:
    name: petlife-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petlife_test}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

debug: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
    enabled: ${SWAGGER_ENABLED:true}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always


rsa:
  public-key: ${PETLIFE_RSA_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoYO2Jb0aRnSIvDKC5CJq5abO1qYZITKN4N3K2RNzmkfe59fq6QZStyzKhP1Sqfb1ITWs4/MNdoTbAr6KqSpPy1fBl3kCSwGkCh3h+78Xz/2uAMaj+keOFBooItITC9yWec+je099rxeYjx3g9frOKMoxfTabnqEyIJr1678qOJ9Qp8v7WtZnDm69fca8Y/lYOdN83XdRUqB3EHexbGdaCuxJd2Wy5C02ZG+ZwoOT51X2hG6w9atNH89QkedeysCVMI/NlgWsP8uhcv4zbo81OxMav7J1fvhyOB5RK0Zoo4hGrGbHF9HOVCV30x5uctSORgz/62DBTRW5CDXHzsb8fQIDAQAB}
  private-key: ${PETLIFE_RSA_PRIVATE_KEY:MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChg7YlvRpGdIi8MoLkImrlps7WphkhMo3g3crZE3OaR97n1+rpBlK3LMqE/VKp9vUhNazj8w12hNsCvoqpKk/LV8GXeQJLAaQKHeH7vxfP/a4AxqP6R44UGigi0hML3JZ5z6N7T32vF5iPHeD1+s4oyjF9NpueoTIgmvXrvyo4n1Cny/ta1mcObr19xrxj+Vg503zdd1FSoHcQd7FsZ1oK7El3ZbLkLTZkb5nCg5PnVfaEbrD1q00fz1CR517KwJUwj82WBaw/y6Fy/jNujzU7Exq/snV++HI4HlErRmijiEasZscX0c5UJXfTHm5y1I5GDP/rYMFNFbkINcfOxvx9AgMBAAECggEADpTB8mk+gILPv1G+EFNtHBtxi95F4YHbXiQXxn4jjxeS75JGElBwUjoYdGYcOtzhJ2TdnVyZaAw5a2eBRCFeP8jF4ONbSiM1SHaHKr+HKk9IEKjeL9+a24S6/93AO29oJEoTA7Ra794s9yqm3v4L85HBYwD1jp4V1Oy4a9Z/vMm8ZJxdBgfvuejL/Y351IcaJLXZ9LBGRPAdGjhT5VVopL6xx78bbTKZ1vNmkkNAnwe311vZtYjMMhJKWh9gIEDkedPEwkbB8ZMHbV9WCHkxvHiTPqlASLDR867fpSzfpHB3FVIyS01qEJ1lrG5he4lWC1Ix6D3CsX+4yQR86rQUsQKBgQDZ0NcTkBPWMEl1d5rYDD9rxE0xS8PgXHgmzE1j0SNUMUjxE0YIUkmDU2kbDQIykIUFHTa22vLerOkdd6Y7peE/QUfK7V+s2v4DIYJyndNHEA2AL9l0ov0LXx+kUZsHX/3Xmvg23liJKr2S+jKixDYHK/h4/qVOsrnNMmA6Og43GQKBgQC91C0mKyopdkGVX6GWkRqJGa/N77bRa5KO8seUj3Y3NpYlrr7jWNab6lqx9DAa0gJtK5uJHOIykgggLRwcLBNr4lVVXX1hXJVTW/yA7+vMWKgy26IY+/QEq6gaCXsOeh6mdiDC09ODVnjSOkB/gsu38hFbydmsfETu5aMavLlRBQKBgQCc4N+nhWPkJs8hvc1WwiuDkNUQJkOj+rXHK+qpc94AK6cfiwQrxiiQX6kaBJqKlLBZ6JqZxMScQOl9gcnGuEitaHUu4RzBwNCmrKHpr2aWjidLJit26FVctVxy2xvPigGoIkOYMTiPQqtbiryhorRPIgpKCw5AylUsR5YrGdlXMQKBgGIAKhbsbeXd4Vnmdxuuac6h7jsZKH7RVGZsPFEcB2HV0oo9vtrMQG9Z+9ynPjZ6eTo3KyMMQFLvRTanUz3QG260+G0LyPD8xTK16JQASPHES4GGFhdj68SFglF+14LP1QcHMT6j8Sx69gFChY3OzrF2TTPf73q25TeYYi4phFqpAoGBAK3ypVb0fQ6EweG3+gnGgrRYHcy/BFId6yRmub4yPnDXi82F+TCy7puJSGwuI6K20trdIUG/fANURaLnKzZcjdKq88h88ShKpCWI91wJ4H95/yPGkn3UY8bIJBLnoGVfhZzjdlqFn/H+mYmc2IkZT57588DDG+hUu17Me/kw5PSx}
